### ISSUE TITLE
"require" errors when trying to run for the first time

### ISSUE THREAD

**Issue by morganestes** [rposborne/gitwakatime#4]
Following the instructions in the [README](https://github.com/rposborne/gitwakatime/blob/master/README.md), I installed the gem and tried to run it, but keep getting a load error that prevents me from doing anything with it:

```console
/usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require': cannot load such file -- pry (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/gitwakatime-0.2.2/lib/gitwakatime/cli.rb:11:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/gitwakatime-0.2.2/lib/gitwakatime.rb:22:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/gitwakatime-0.2.2/bin/gitwakatime:4:in `require_relative'
	from /usr/local/lib/ruby/gems/2.2.0/gems/gitwakatime-0.2.2/bin/gitwakatime:4:in `<top (required)>'
	from /usr/local/bin/gitwakatime:23:in `load'
	from /usr/local/bin/gitwakatime:23:in `<main>'
```

Some research led me to think that bundler might be an issue, so I ran `bundle` from within `/usr/local/lib/ruby/gems/2.2.0/gems/gitwakatime-0.2.2`. After that ran successfully ("Bundle complete! 7 Gemfile dependencies, 39 gems now installed."), I ran `gitwakatime init` again, with new results:

```console
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
What is your wakatime api key? ( Get it here https://wakatime.com/settings): <my api key here>
Adding .wakatime.yml to home directory
      create  /Users/morganestes/.wakatime.yml
``` 

So far that seems to be working, although I get the initial `WARN: Unresolved specs during Gem::Specification.reset:` every time I run a `gitwakatime` command, but I'd like to be sure I'm not missing something by doing this.

**Comment by rposborne** [comment]
Yup getting the issue as well.   I use this gem to pass structured data into another gem that passes it to quickbooks so I don't use it's directly interface that often.
