### ISSUE TITLE
Time not showing at all

### ISSUE THREAD

**Issue by Pszek** [rposborne/gitwakatime#5]
Instead of time I have blank space, everything other is showing up. Could You tell me how can I help You debug it?

**Comment by rposborne** [comment]
@Pszek Have you done the init command to setup the link to Wakatime? Could you also copy and paste the output of the command so I can get a little more context? 

I will note that this so far has been personal project more than anything else so it hasn't been very battle tested.

**Comment by Pszek** [comment]
Yes I've done Init.
I will paste a screen below, cause it looks better than bare, unstyled code.
![zrzut ekranu 2016-01-08 o 11 51 41](https://cloud.githubusercontent.com/assets/10253750/12196371/4e2c2218-b5fe-11e5-8303-094b37fe28b3.png)

**Comment by rposborne** [comment]
@Pszek can you try the reset command,  it's possible the cache has some bad data in it.

**Comment by Pszek** [comment]
I tried that one too. Did you use that on OSX (my current working OS)? Any ideas how can I debug it, or get some logs?

**Comment by akatrevorjay** [comment]
Same here, just installed and inserted my time.

**Comment by akatrevorjay** [comment]
It's a problem with generation:

``sql
sqlite> select * from commited_files limit 1;
1|1|fb9e85e6576bbb407e8ea3b718c8d36bbe87bb7d|2016-01-21 02:44:45.000000||2bad922b941bfb10ba5261c4a3aa4544c6fc9613|<snip>.py||<snip>
sqlite> select distinct time_in_seconds from commited_files;

sqlite> select count(*) from commited_files;
1082
```

**Comment by rposborne** [comment]
@akatrevorjay, thanks for digging a bit. So if I am reading this right.  We generated commited_files but have no timing.   Just out of curiosity, what timezone are you in?  It's a possible we have a shift which could cause a 100% mismatch

**Comment by akatrevorjay** [comment]
Hmm!  I'm EST(-5) personally.
